import { describe, expect, test } from "vitest";
import RunnerStatusEnum from "../models/enums/runner-status-enum";
import { matchRunnersByName } from "./runners-matcher";

describe("matchRunnersByName()", () => {
  const outputRunners = matchRunnersByName(inputRunners, twoDRerunRoutes);

  test("to match runners by name ;)", () => {
    expect(outputRunners).toStrictEqual(expectedRunners);
  });
});

const expectedRunners = [
  {
    id: 1,
    foreignKeys: { twoDRerunRouteIndexNumber: 1 },
    status: "ok",
    firstName: "M",
    lastName: "Kirmula",
    startTime: 1659529800,
    time: 1765,
    legs: [],
    rank: 1,
    timeBehind: 0,
    totalTimeLost: 0,
  },
  {
    id: 2,
    foreignKeys: { twoDRerunRouteIndexNumber: 2 },
    status: "ok",
    firstName: "Lauri",
    lastName: "Sild",
    startTime: 1659529680,
    time: 1796,
    legs: [],
    rank: 2,
    timeBehind: 31,
    totalTimeLost: 0,
  },
  {
    id: 3,
    foreignKeys: { twoDRerunRouteIndexNumber: 3 },
    status: "ok",
    firstName: "Ruslan",
    lastName: "Glibov",
    startTime: 1659528360,
    time: 1802,
    legs: [],
    rank: 3,
    timeBehind: 37,
    totalTimeLost: 0,
  },
  {
    id: 4,
    foreignKeys: { twoDRerunRouteIndexNumber: 4 },
    status: "ok",
    firstName: "Michal",
    lastName: "Olejnik",
    startTime: 1659529560,
    time: 1806,
    legs: [],
    rank: 4,
    timeBehind: 41,
    totalTimeLost: 0,
  },
  {
    id: 5,
    foreignKeys: { twoDRerunRouteIndexNumber: 5 },
    status: "ok",
    firstName: "Daniel",
    lastName: "Hubmann",
    startTime: 1659528000,
    time: 1838,
    legs: [],
    rank: 5,
    timeBehind: 73,
    totalTimeLost: 0,
  },
  {
    id: 6,
    foreignKeys: { twoDRerunRouteIndexNumber: 6 },
    status: "ok",
    firstName: "Eskil",
    lastName: "Kinneberg",
    startTime: 1659529200,
    time: 1844,
    legs: [],
    rank: 6,
    timeBehind: 79,
    totalTimeLost: 0,
  },
  {
    id: 7,
    foreignKeys: { twoDRerunRouteIndexNumber: 7 },
    status: "ok",
    firstName: "Max Peter",
    lastName: "Bejmer",
    startTime: 1659526560,
    time: 1896,
    legs: [],
    rank: 7,
    timeBehind: 131,
    totalTimeLost: 0,
  },
  {
    id: 8,
    foreignKeys: { twoDRerunRouteIndexNumber: 8 },
    status: "ok",
    firstName: "Rasmus Moeller",
    lastName: "Jess",
    startTime: 1659528240,
    time: 1919,
    legs: [],
    rank: 8,
    timeBehind: 154,
    totalTimeLost: 0,
  },
  {
    id: 9,
    foreignKeys: { twoDRerunRouteIndexNumber: 9 },
    status: "ok",
    firstName: "Bojan",
    lastName: "Blumenstein",
    startTime: 1659527880,
    time: 1942,
    legs: [],
    rank: 9,
    timeBehind: 177,
    totalTimeLost: 0,
  },
  {
    id: 10,
    foreignKeys: { twoDRerunRouteIndexNumber: 10 },
    status: "ok",
    firstName: "Loic",
    lastName: "Capbern",
    startTime: 1659525840,
    time: 1960,
    legs: [],
    rank: 10,
    timeBehind: 195,
    totalTimeLost: 0,
  },
  {
    id: 11,
    foreignKeys: { twoDRerunRouteIndexNumber: 11 },
    status: "ok",
    firstName: "Nicolas",
    lastName: "Rio",
    startTime: 1659528480,
    time: 1999,
    legs: [],
    rank: 11,
    timeBehind: 234,
    totalTimeLost: 0,
  },
  {
    id: 12,
    foreignKeys: { twoDRerunRouteIndexNumber: 12 },
    status: "ok",
    firstName: "Kristo",
    lastName: "Heinmann",
    startTime: 1659527520,
    time: 2002,
    legs: [],
    rank: 12,
    timeBehind: 237,
    totalTimeLost: 0,
  },
  {
    id: 13,
    foreignKeys: { twoDRerunRouteIndexNumber: 13 },
    status: "ok",
    firstName: "Elias",
    lastName: "Jonsson",
    startTime: 1659525480,
    time: 2003,
    legs: [],
    rank: 13,
    timeBehind: 238,
    totalTimeLost: 0,
  },
  {
    id: 14,
    foreignKeys: { twoDRerunRouteIndexNumber: 14 },
    status: "ok",
    firstName: "Arturs",
    lastName: "Paulins",
    startTime: 1659526440,
    time: 2019,
    legs: [],
    rank: 14,
    timeBehind: 254,
    totalTimeLost: 0,
  },
  {
    id: 15,
    foreignKeys: { twoDRerunRouteIndexNumber: 15 },
    status: "ok",
    firstName: "Milos",
    lastName: "Nykodym",
    startTime: 1659526800,
    time: 2030,
    legs: [],
    rank: 15,
    timeBehind: 265,
    totalTimeLost: 0,
  },
  {
    id: 16,
    foreignKeys: { twoDRerunRouteIndexNumber: 16 },
    status: "ok",
    firstName: "Edgars",
    lastName: "Bertuks",
    startTime: 1659528600,
    time: 2048,
    legs: [],
    rank: 16,
    timeBehind: 283,
    totalTimeLost: 0,
  },
  {
    id: 17,
    foreignKeys: { twoDRerunRouteIndexNumber: 17 },
    status: "ok",
    firstName: "Vegard Jarvis",
    lastName: "Westergard",
    startTime: 1659529320,
    time: 2050,
    legs: [],
    rank: 17,
    timeBehind: 285,
    totalTimeLost: 0,
  },
  {
    id: 18,
    foreignKeys: { twoDRerunRouteIndexNumber: 18 },
    status: "ok",
    firstName: "Jonas",
    lastName: "Egger",
    startTime: 1659527760,
    time: 2072,
    legs: [],
    rank: 18,
    timeBehind: 307,
    totalTimeLost: 0,
  },
  {
    id: 19,
    foreignKeys: { twoDRerunRouteIndexNumber: 19 },
    status: "ok",
    firstName: "Timo",
    lastName: "Suter",
    startTime: 1659525720,
    time: 2081,
    legs: [],
    rank: 19,
    timeBehind: 316,
    totalTimeLost: 0,
  },
  {
    id: 20,
    foreignKeys: { twoDRerunRouteIndexNumber: 20 },
    status: "ok",
    firstName: "Maxime",
    lastName: "Rauturier",
    startTime: 1659526920,
    time: 2086,
    legs: [],
    rank: 20,
    timeBehind: 321,
    totalTimeLost: 0,
  },
  {
    id: 21,
    foreignKeys: { twoDRerunRouteIndexNumber: 21 },
    status: "ok",
    firstName: "Eetu",
    lastName: "Savolainen",
    startTime: 1659525120,
    time: 2095,
    legs: [],
    rank: 21,
    timeBehind: 330,
    totalTimeLost: 0,
  },
  {
    id: 22,
    foreignKeys: {},
    status: "ok",
    firstName: "Laurits Bidstrup",
    lastName: "Moller",
    startTime: 1659526200,
    time: 2107,
    legs: [],
    rank: 22,
    timeBehind: 342,
    totalTimeLost: 0,
  },
  {
    id: 23,
    foreignKeys: { twoDRerunRouteIndexNumber: 23 },
    status: "ok",
    firstName: "Topi",
    lastName: "Syrjalainen",
    startTime: 1659527160,
    time: 2116,
    legs: [],
    rank: 23,
    timeBehind: 351,
    totalTimeLost: 0,
  },
  {
    id: 24,
    foreignKeys: {},
    status: "ok",
    firstName: "P",
    lastName: "Llorens Caellas",
    startTime: 1659527400,
    time: 2131,
    legs: [],
    rank: 24,
    timeBehind: 366,
    totalTimeLost: 0,
  },
  {
    id: 25,
    foreignKeys: { twoDRerunRouteIndexNumber: 25 },
    status: "ok",
    firstName: "Hans Petter",
    lastName: "Mathisen",
    startTime: 1659526320,
    time: 2140,
    legs: [],
    rank: 25,
    timeBehind: 375,
    totalTimeLost: 0,
  },
  {
    id: 26,
    foreignKeys: { twoDRerunRouteIndexNumber: 26 },
    status: "ok",
    firstName: "Alastair",
    lastName: "George",
    startTime: 1659529920,
    time: 2144,
    legs: [],
    rank: 26,
    timeBehind: 379,
    totalTimeLost: 0,
  },
  {
    id: 27,
    foreignKeys: { twoDRerunRouteIndexNumber: 27 },
    status: "ok",
    firstName: "Joshua",
    lastName: "Dudley",
    startTime: 1659524640,
    time: 2146,
    legs: [],
    rank: 27,
    timeBehind: 381,
    totalTimeLost: 0,
  },
  {
    id: 28,
    foreignKeys: { twoDRerunRouteIndexNumber: 28 },
    status: "ok",
    firstName: "Florian",
    lastName: "Kurz",
    startTime: 1659524760,
    time: 2215,
    legs: [],
    rank: 28,
    timeBehind: 450,
    totalTimeLost: 0,
  },
  {
    id: 29,
    foreignKeys: { twoDRerunRouteIndexNumber: 29 },
    status: "ok",
    firstName: "Uku Laur",
    lastName: "Tali",
    startTime: 1659524400,
    time: 2308,
    legs: [],
    rank: 29,
    timeBehind: 543,
    totalTimeLost: 0,
  },
  {
    id: 30,
    foreignKeys: { twoDRerunRouteIndexNumber: 30 },
    status: "ok",
    firstName: "Alexander",
    lastName: "Chepelin",
    startTime: 1659528840,
    time: 2331,
    legs: [],
    rank: 30,
    timeBehind: 566,
    totalTimeLost: 0,
  },
  {
    id: 31,
    foreignKeys: { twoDRerunRouteIndexNumber: 31 },
    status: "ok",
    firstName: "Yannick",
    lastName: "Michiels",
    startTime: 1659528720,
    time: 2355,
    legs: [],
    rank: 31,
    timeBehind: 590,
    totalTimeLost: 0,
  },
  {
    id: 32,
    foreignKeys: { twoDRerunRouteIndexNumber: 32 },
    status: "ok",
    firstName: "Daniel",
    lastName: "Pompura",
    startTime: 1659527280,
    time: 2377,
    legs: [],
    rank: 32,
    timeBehind: 612,
    totalTimeLost: 0,
  },
  {
    id: 33,
    foreignKeys: { twoDRerunRouteIndexNumber: 33 },
    status: "ok",
    firstName: "Francesco",
    lastName: "Mariani",
    startTime: 1659530040,
    time: 2424,
    legs: [],
    rank: 33,
    timeBehind: 659,
    totalTimeLost: 0,
  },
  {
    id: 34,
    foreignKeys: { twoDRerunRouteIndexNumber: 34 },
    status: "ok",
    firstName: "Robert",
    lastName: "Merl",
    startTime: 1659526680,
    time: 2600,
    legs: [],
    rank: 34,
    timeBehind: 835,
    totalTimeLost: 0,
  },
  {
    id: 35,
    foreignKeys: { twoDRerunRouteIndexNumber: 35 },
    status: "ok",
    firstName: "Peleg",
    lastName: "Mitzafon",
    startTime: 1659529440,
    time: 2625,
    legs: [],
    rank: 35,
    timeBehind: 860,
    totalTimeLost: 0,
  },
  {
    id: 36,
    foreignKeys: { twoDRerunRouteIndexNumber: 36 },
    status: "ok",
    firstName: "Mikolaj",
    lastName: "Dutkowski",
    startTime: 1659525000,
    time: 2637,
    legs: [],
    rank: 36,
    timeBehind: 872,
    totalTimeLost: 0,
  },
  {
    id: 37,
    foreignKeys: { twoDRerunRouteIndexNumber: 37 },
    status: "ok",
    firstName: "Anton",
    lastName: "Silier",
    startTime: 1659525600,
    time: 2829,
    legs: [],
    rank: 37,
    timeBehind: 1064,
    totalTimeLost: 0,
  },
  {
    id: 38,
    foreignKeys: { twoDRerunRouteIndexNumber: 38 },
    status: "ok",
    firstName: "Stanislav",
    lastName: "Polianytsia",
    startTime: 1659524520,
    time: 2874,
    legs: [],
    rank: 38,
    timeBehind: 1109,
    totalTimeLost: 0,
  },
  {
    id: 39,
    foreignKeys: { twoDRerunRouteIndexNumber: 39 },
    status: "ok",
    firstName: "Alvaro",
    lastName: "Garcia Bernabeu",
    startTime: 1659525240,
    time: 3040,
    legs: [],
    rank: 39,
    timeBehind: 1275,
    totalTimeLost: 0,
  },
  {
    id: 40,
    foreignKeys: { twoDRerunRouteIndexNumber: 40 },
    status: "ok",
    firstName: "Michael",
    lastName: "Van Baelen",
    startTime: 1659527640,
    time: 3100,
    legs: [],
    rank: 40,
    timeBehind: 1335,
    totalTimeLost: 0,
  },
  {
    id: 41,
    foreignKeys: { twoDRerunRouteIndexNumber: 41 },
    status: "ok",
    firstName: "Toby",
    lastName: "Scott",
    startTime: 1659528960,
    time: 3119,
    legs: [],
    rank: 41,
    timeBehind: 1354,
    totalTimeLost: 0,
  },
  {
    id: 42,
    foreignKeys: { twoDRerunRouteIndexNumber: 42 },
    status: "ok",
    firstName: "Shunsuke",
    lastName: "Shimizu",
    startTime: 1659527040,
    time: 3711,
    legs: [],
    rank: 42,
    timeBehind: 1946,
    totalTimeLost: 0,
  },
  {
    id: 43,
    foreignKeys: { twoDRerunRouteIndexNumber: 43 },
    status: "ok",
    firstName: "Vasco",
    lastName: "Mendes",
    startTime: 1659526080,
    time: 3744,
    legs: [],
    rank: 43,
    timeBehind: 1979,
    totalTimeLost: 0,
  },
  {
    id: 44,
    foreignKeys: { twoDRerunRouteIndexNumber: 44 },
    status: "ok",
    firstName: "Valentin",
    lastName: "Shishkov",
    startTime: 1659524880,
    time: 3996,
    legs: [],
    rank: 44,
    timeBehind: 2231,
    totalTimeLost: 0,
  },
  {
    id: 45,
    foreignKeys: { twoDRerunRouteIndexNumber: 45 },
    status: "ok",
    firstName: "Kai Yui Hubert",
    lastName: "Yam",
    startTime: 1659525960,
    time: 5475,
    legs: [],
    rank: 45,
    timeBehind: 3710,
    totalTimeLost: 0,
  },
  {
    id: 46,
    foreignKeys: { twoDRerunRouteIndexNumber: 46 },
    status: "not-ok",
    firstName: "Martin",
    lastName: "Regborn",
    startTime: 1659529080,
    time: null,
    legs: [],
    rank: null,
    timeBehind: null,
    totalTimeLost: 0,
  },
  {
    id: 47,
    foreignKeys: { twoDRerunRouteIndexNumber: 47 },
    status: "not-ok",
    firstName: "Vilius",
    lastName: "Aleliunas",
    startTime: 1659528120,
    time: null,
    legs: [],
    rank: null,
    timeBehind: null,
    totalTimeLost: 0,
  },
  {
    id: 48,
    foreignKeys: { twoDRerunRouteIndexNumber: 48 },
    status: "not-ok",
    firstName: "Angus",
    lastName: "Haines",
    startTime: 1659525360,
    time: null,
    legs: [],
    rank: null,
    timeBehind: null,
    totalTimeLost: 0,
  },
];

const twoDRerunRoutes = [
  {
    indexnumber: 1,
    runnername: "Kirmula Miika",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 2,
    runnername: "S Lauri",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 3,
    runnername: "Glibov Ruslan",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 4,
    runnername: "Olejnik Michal",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 5,
    runnername: "Hubmann Daniel",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 6,
    runnername: "Kinneberg Eskil",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 7,
    runnername: "Bejmer Max Peter",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 8,
    runnername: "Jess R Moeller",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 9,
    runnername: "Blumenstein Bojan",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 10,
    runnername: "Capbern Loic",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 11,
    runnername: "Rio Nicolas",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 12,
    runnername: "Heinmann Kristo",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 13,
    runnername: "Jonsson Elias",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 14,
    runnername: "Paulins Arturs",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 15,
    runnername: "Nykodym Milos",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 16,
    runnername: "Bertuks Edgars",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 17,
    runnername: "Westergard Vegard Jarvis",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 18,
    runnername: "Egger Jonas",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 19,
    runnername: "Suter Timo",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 20,
    runnername: "Rauturier Maxime",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 21,
    runnername: "Savolainen Eetu",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 22,
    runnername: "M L Bidstrup",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 23,
    runnername: "Syrjalainen Topi",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 24,
    runnername: "Llorens C Pau",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 25,
    runnername: "Mathisen Hans Petter",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 26,
    runnername: "George Alastair",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 27,
    runnername: "Dudley Joshua",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 28,
    runnername: "Kurz Florian",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 29,
    runnername: "Tali Uku Laur",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 30,
    runnername: "Chepelin Alexander",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 31,
    runnername: "Michiels Yannick",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 32,
    runnername: "Pompura Daniel",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 33,
    runnername: "Mariani Francesco",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 34,
    runnername: "Merl Robert",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 35,
    runnername: "Mitzafon Peleg",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 36,
    runnername: "Dutkowski Mikolaj",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 37,
    runnername: "Silier Anton",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 38,
    runnername: "Polianytsia Stanislav",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 39,
    runnername: "Garcia Bernabeu Alvaro",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 40,
    runnername: "Van Baelen Michael",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 41,
    runnername: "Scott Toby",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 42,
    runnername: "Shimizu Shunsuke",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 43,
    runnername: "Mendes Vasco",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 44,
    runnername: "Shishkov Valentin",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 45,
    runnername: "Yam Kai Yui Hubert",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 46,
    runnername: "Regborn Martin",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 47,
    runnername: "Aleliunas Vilius",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 48,
    runnername: "Haines Angus",
    latarray: [],
    lngarray: [],
    timearray: [],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
];

const inputRunners = [
  {
    id: 1,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "M",
    lastName: "Kirmula",
    startTime: 1659529800,
    time: 1765,
    legs: [],
    rank: 1,
    timeBehind: 0,
    totalTimeLost: 0,
  },
  {
    id: 2,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Lauri",
    lastName: "Sild",
    startTime: 1659529680,
    time: 1796,
    legs: [],
    rank: 2,
    timeBehind: 31,
    totalTimeLost: 0,
  },
  {
    id: 3,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Ruslan",
    lastName: "Glibov",
    startTime: 1659528360,
    time: 1802,
    legs: [],
    rank: 3,
    timeBehind: 37,
    totalTimeLost: 0,
  },
  {
    id: 4,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Michal",
    lastName: "Olejnik",
    startTime: 1659529560,
    time: 1806,
    legs: [],
    rank: 4,
    timeBehind: 41,
    totalTimeLost: 0,
  },
  {
    id: 5,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Daniel",
    lastName: "Hubmann",
    startTime: 1659528000,
    time: 1838,
    legs: [],
    rank: 5,
    timeBehind: 73,
    totalTimeLost: 0,
  },
  {
    id: 6,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Eskil",
    lastName: "Kinneberg",
    startTime: 1659529200,
    time: 1844,
    legs: [],
    rank: 6,
    timeBehind: 79,
    totalTimeLost: 0,
  },
  {
    id: 7,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Max Peter",
    lastName: "Bejmer",
    startTime: 1659526560,
    time: 1896,
    legs: [],
    rank: 7,
    timeBehind: 131,
    totalTimeLost: 0,
  },
  {
    id: 8,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Rasmus Moeller",
    lastName: "Jess",
    startTime: 1659528240,
    time: 1919,
    legs: [],
    rank: 8,
    timeBehind: 154,
    totalTimeLost: 0,
  },
  {
    id: 9,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Bojan",
    lastName: "Blumenstein",
    startTime: 1659527880,
    time: 1942,
    legs: [],
    rank: 9,
    timeBehind: 177,
    totalTimeLost: 0,
  },
  {
    id: 10,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Loic",
    lastName: "Capbern",
    startTime: 1659525840,
    time: 1960,
    legs: [],
    rank: 10,
    timeBehind: 195,
    totalTimeLost: 0,
  },
  {
    id: 11,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Nicolas",
    lastName: "Rio",
    startTime: 1659528480,
    time: 1999,
    legs: [],
    rank: 11,
    timeBehind: 234,
    totalTimeLost: 0,
  },
  {
    id: 12,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Kristo",
    lastName: "Heinmann",
    startTime: 1659527520,
    time: 2002,
    legs: [],
    rank: 12,
    timeBehind: 237,
    totalTimeLost: 0,
  },
  {
    id: 13,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Elias",
    lastName: "Jonsson",
    startTime: 1659525480,
    time: 2003,
    legs: [],
    rank: 13,
    timeBehind: 238,
    totalTimeLost: 0,
  },
  {
    id: 14,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Arturs",
    lastName: "Paulins",
    startTime: 1659526440,
    time: 2019,
    legs: [],
    rank: 14,
    timeBehind: 254,
    totalTimeLost: 0,
  },
  {
    id: 15,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Milos",
    lastName: "Nykodym",
    startTime: 1659526800,
    time: 2030,
    legs: [],
    rank: 15,
    timeBehind: 265,
    totalTimeLost: 0,
  },
  {
    id: 16,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Edgars",
    lastName: "Bertuks",
    startTime: 1659528600,
    time: 2048,
    legs: [],
    rank: 16,
    timeBehind: 283,
    totalTimeLost: 0,
  },
  {
    id: 17,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Vegard Jarvis",
    lastName: "Westergard",
    startTime: 1659529320,
    time: 2050,
    legs: [],
    rank: 17,
    timeBehind: 285,
    totalTimeLost: 0,
  },
  {
    id: 18,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Jonas",
    lastName: "Egger",
    startTime: 1659527760,
    time: 2072,
    legs: [],
    rank: 18,
    timeBehind: 307,
    totalTimeLost: 0,
  },
  {
    id: 19,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Timo",
    lastName: "Suter",
    startTime: 1659525720,
    time: 2081,
    legs: [],
    rank: 19,
    timeBehind: 316,
    totalTimeLost: 0,
  },
  {
    id: 20,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Maxime",
    lastName: "Rauturier",
    startTime: 1659526920,
    time: 2086,
    legs: [],
    rank: 20,
    timeBehind: 321,
    totalTimeLost: 0,
  },
  {
    id: 21,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Eetu",
    lastName: "Savolainen",
    startTime: 1659525120,
    time: 2095,
    legs: [],
    rank: 21,
    timeBehind: 330,
    totalTimeLost: 0,
  },
  {
    id: 22,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Laurits Bidstrup",
    lastName: "Moller",
    startTime: 1659526200,
    time: 2107,
    legs: [],
    rank: 22,
    timeBehind: 342,
    totalTimeLost: 0,
  },
  {
    id: 23,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Topi",
    lastName: "Syrjalainen",
    startTime: 1659527160,
    time: 2116,
    legs: [],
    rank: 23,
    timeBehind: 351,
    totalTimeLost: 0,
  },
  {
    id: 24,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "P",
    lastName: "Llorens Caellas",
    startTime: 1659527400,
    time: 2131,
    legs: [],
    rank: 24,
    timeBehind: 366,
    totalTimeLost: 0,
  },
  {
    id: 25,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Hans Petter",
    lastName: "Mathisen",
    startTime: 1659526320,
    time: 2140,
    legs: [],
    rank: 25,
    timeBehind: 375,
    totalTimeLost: 0,
  },
  {
    id: 26,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Alastair",
    lastName: "George",
    startTime: 1659529920,
    time: 2144,
    legs: [],
    rank: 26,
    timeBehind: 379,
    totalTimeLost: 0,
  },
  {
    id: 27,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Joshua",
    lastName: "Dudley",
    startTime: 1659524640,
    time: 2146,
    legs: [],
    rank: 27,
    timeBehind: 381,
    totalTimeLost: 0,
  },
  {
    id: 28,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Florian",
    lastName: "Kurz",
    startTime: 1659524760,
    time: 2215,
    legs: [],
    rank: 28,
    timeBehind: 450,
    totalTimeLost: 0,
  },
  {
    id: 29,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Uku Laur",
    lastName: "Tali",
    startTime: 1659524400,
    time: 2308,
    legs: [],
    rank: 29,
    timeBehind: 543,
    totalTimeLost: 0,
  },
  {
    id: 30,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Alexander",
    lastName: "Chepelin",
    startTime: 1659528840,
    time: 2331,
    legs: [],
    rank: 30,
    timeBehind: 566,
    totalTimeLost: 0,
  },
  {
    id: 31,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Yannick",
    lastName: "Michiels",
    startTime: 1659528720,
    time: 2355,
    legs: [],
    rank: 31,
    timeBehind: 590,
    totalTimeLost: 0,
  },
  {
    id: 32,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Daniel",
    lastName: "Pompura",
    startTime: 1659527280,
    time: 2377,
    legs: [],
    rank: 32,
    timeBehind: 612,
    totalTimeLost: 0,
  },
  {
    id: 33,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Francesco",
    lastName: "Mariani",
    startTime: 1659530040,
    time: 2424,
    legs: [],
    rank: 33,
    timeBehind: 659,
    totalTimeLost: 0,
  },
  {
    id: 34,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Robert",
    lastName: "Merl",
    startTime: 1659526680,
    time: 2600,
    legs: [],
    rank: 34,
    timeBehind: 835,
    totalTimeLost: 0,
  },
  {
    id: 35,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Peleg",
    lastName: "Mitzafon",
    startTime: 1659529440,
    time: 2625,
    legs: [],
    rank: 35,
    timeBehind: 860,
    totalTimeLost: 0,
  },
  {
    id: 36,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Mikolaj",
    lastName: "Dutkowski",
    startTime: 1659525000,
    time: 2637,
    legs: [],
    rank: 36,
    timeBehind: 872,
    totalTimeLost: 0,
  },
  {
    id: 37,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Anton",
    lastName: "Silier",
    startTime: 1659525600,
    time: 2829,
    legs: [],
    rank: 37,
    timeBehind: 1064,
    totalTimeLost: 0,
  },
  {
    id: 38,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Stanislav",
    lastName: "Polianytsia",
    startTime: 1659524520,
    time: 2874,
    legs: [],
    rank: 38,
    timeBehind: 1109,
    totalTimeLost: 0,
  },
  {
    id: 39,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Alvaro",
    lastName: "Garcia Bernabeu",
    startTime: 1659525240,
    time: 3040,
    legs: [],
    rank: 39,
    timeBehind: 1275,
    totalTimeLost: 0,
  },
  {
    id: 40,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Michael",
    lastName: "Van Baelen",
    startTime: 1659527640,
    time: 3100,
    legs: [],
    rank: 40,
    timeBehind: 1335,
    totalTimeLost: 0,
  },
  {
    id: 41,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Toby",
    lastName: "Scott",
    startTime: 1659528960,
    time: 3119,
    legs: [],
    rank: 41,
    timeBehind: 1354,
    totalTimeLost: 0,
  },
  {
    id: 42,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Shunsuke",
    lastName: "Shimizu",
    startTime: 1659527040,
    time: 3711,
    legs: [],
    rank: 42,
    timeBehind: 1946,
    totalTimeLost: 0,
  },
  {
    id: 43,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Vasco",
    lastName: "Mendes",
    startTime: 1659526080,
    time: 3744,
    legs: [],
    rank: 43,
    timeBehind: 1979,
    totalTimeLost: 0,
  },
  {
    id: 44,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Valentin",
    lastName: "Shishkov",
    startTime: 1659524880,
    time: 3996,
    legs: [],
    rank: 44,
    timeBehind: 2231,
    totalTimeLost: 0,
  },
  {
    id: 45,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Kai Yui Hubert",
    lastName: "Yam",
    startTime: 1659525960,
    time: 5475,
    legs: [],
    rank: 45,
    timeBehind: 3710,
    totalTimeLost: 0,
  },
  {
    id: 46,
    foreignKeys: {},
    status: RunnerStatusEnum.NOT_OK,
    firstName: "Martin",
    lastName: "Regborn",
    startTime: 1659529080,
    time: null,
    legs: [],
    rank: null,
    timeBehind: null,
    totalTimeLost: 0,
  },
  {
    id: 47,
    foreignKeys: {},
    status: RunnerStatusEnum.NOT_OK,
    firstName: "Vilius",
    lastName: "Aleliunas",
    startTime: 1659528120,
    time: null,
    legs: [],
    rank: null,
    timeBehind: null,
    totalTimeLost: 0,
  },
  {
    id: 48,
    foreignKeys: {},
    status: RunnerStatusEnum.NOT_OK,
    firstName: "Angus",
    lastName: "Haines",
    startTime: 1659525360,
    time: null,
    legs: [],
    rank: null,
    timeBehind: null,
    totalTimeLost: 0,
  },
];
