import { describe, expect, test } from "vitest";
import { parseIOFXML3SplitTimesFile } from "./iof-xml-3";
import { IOF_XML_2_SPLIT_TIMES } from "./mocks/iof-xml-2-split-times";
import { IOF_XML_3_SPLIT_TIMES } from "./mocks/iof-xml-3-split-times";

describe("parseIOFXML3SplitTimesFile()", () => {
  test("throw error when iof xml version is not 3.0.", () => {
    const parser = new DOMParser();
    const xmlDoc2 = parser.parseFromString(IOF_XML_2_SPLIT_TIMES, "text/xml");

    expect(() =>
      parseIOFXML3SplitTimesFile(xmlDoc2, "Men-A", "+02:00", 0)
    ).toThrow();
  });

  test("expecte first runner to be strict equal.", () => {
    const parser = new DOMParser();
    const xmlDoc3 = parser.parseFromString(IOF_XML_3_SPLIT_TIMES, "text/xml");

    expect(
      parseIOFXML3SplitTimesFile(xmlDoc3, "Men-A", "+02:00", 0)[0]
    ).toStrictEqual(expected);
  });
});

const expected = {
  id: 1,
  foreignKeys: {},
  status: "ok",
  firstName: "Miika",
  lastName: "Kirmula",
  startTime: 1659529800,
  time: 1765,
  legs: [
    {
      controlCode: 101,
      timeOverall: 74,
      time: 74,
      rankSplit: 2,
      timeBehindSplit: 3,
      rankOverall: 2,
      timeBehindOverall: 3,
      timeBehindSuperman: 0,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      controlCode: 105,
      timeOverall: 222,
      time: 148,
      rankSplit: 6,
      timeBehindSplit: 8,
      rankOverall: 1,
      timeBehindOverall: 0,
      timeBehindSuperman: 0,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      controlCode: 107,
      timeOverall: 475,
      time: 253,
      rankSplit: 17,
      timeBehindSplit: 44,
      rankOverall: 6,
      timeBehindOverall: 39,
      timeBehindSuperman: 0,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      controlCode: 109,
      timeOverall: 523,
      time: 48,
      rankSplit: 7,
      timeBehindSplit: 4,
      rankOverall: 5,
      timeBehindOverall: 41,
      timeBehindSuperman: 0,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      controlCode: 110,
      timeOverall: 676,
      time: 153,
      rankSplit: 39,
      timeBehindSplit: 49,
      rankOverall: 11,
      timeBehindOverall: 69,
      timeBehindSuperman: 0,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      controlCode: 113,
      timeOverall: 751,
      time: 75,
      rankSplit: 1,
      timeBehindSplit: 0,
      rankOverall: 8,
      timeBehindOverall: 63,
      timeBehindSuperman: 0,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      controlCode: 115,
      timeOverall: 948,
      time: 197,
      rankSplit: 3,
      timeBehindSplit: 1,
      rankOverall: 4,
      timeBehindOverall: 54,
      timeBehindSuperman: 0,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      controlCode: 116,
      timeOverall: 998,
      time: 50,
      rankSplit: 9,
      timeBehindSplit: 5,
      rankOverall: 4,
      timeBehindOverall: 58,
      timeBehindSuperman: 0,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      controlCode: 118,
      timeOverall: 1208,
      time: 210,
      rankSplit: 3,
      timeBehindSplit: 4,
      rankOverall: 4,
      timeBehindOverall: 62,
      timeBehindSuperman: 0,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      controlCode: 121,
      timeOverall: 1288,
      time: 80,
      rankSplit: 12,
      timeBehindSplit: 10,
      rankOverall: 4,
      timeBehindOverall: 71,
      timeBehindSuperman: 0,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      controlCode: 123,
      timeOverall: 1342,
      time: 54,
      rankSplit: 1,
      timeBehindSplit: 0,
      rankOverall: 3,
      timeBehindOverall: 28,
      timeBehindSuperman: 0,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      controlCode: 125,
      timeOverall: 1479,
      time: 137,
      rankSplit: 2,
      timeBehindSplit: 1,
      rankOverall: 3,
      timeBehindOverall: 11,
      timeBehindSuperman: 0,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      controlCode: 127,
      timeOverall: 1579,
      time: 100,
      rankSplit: 6,
      timeBehindSplit: 16,
      rankOverall: 3,
      timeBehindOverall: 81,
      timeBehindSuperman: 0,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      controlCode: 130,
      timeOverall: 1696,
      time: 117,
      rankSplit: 1,
      timeBehindSplit: 0,
      rankOverall: 2,
      timeBehindOverall: 71,
      timeBehindSuperman: 0,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      controlCode: 100,
      timeOverall: 1741,
      time: 45,
      rankSplit: 1,
      timeBehindSplit: 0,
      rankOverall: 2,
      timeBehindOverall: 69,
      timeBehindSuperman: 0,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
  ],
  rank: 1,
  timeBehind: 0,
  totalTimeLost: 0,
};
